# WhatATheme
markdown: kramdown

# URL of the Site
url: https://ctfesc.github.io
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: CTFESC
# Description of the Site
description: Comunidad de hacking ético de la FES Cuatitlán
# URL of Image of the Site
site-image: /assets/images/ctfesc_flags.png
# Keywords of the Site
site-keywords: Ciberseguridad, FESC, Hacking, CTF
# URL for the Image of custom Favicon
favicon-url: /assets/images/ctfesc_flags_transp.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# matrix
heroimage: https://cdn.pixabay.com/photo/2016/10/12/19/50/matrix-1735640_960_720.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: ctfesc@protonmail.com
twitter_username:
instagram_username: 
linkedin_username: 
github_username: 
youtube_channel_id: ctfesc
reddit_username: 
discord_server: JaU8YX59vV

# Google Analytics
google-analytics:

# Disqus
disqus-shortname: /

# Name of the Author
author-name: CTFESC
# URL for the Image of the Author
author-image: /assets/images/ctfesc_flags.png
# 60 Words About the Author
author-about: Somos una comunidad conformada por estudiantes de la Facultad de Estudios Superiores Cuautitlán interesados en la <b>Ciberseguridad</b> y el <b>Hacking Ético</b>. Impulsamos el aprendizaje autodidacta a través de compartir conocimiento en la <b>resolución de retos y máquinas</b> de plataformas dedicadas al Pentesting, como<a href="https://hackthebox.com" target="_blank">Hack The Box</a> y<a href="https://tryhackme.com" target="_blank">Try Hack Me</a>. <br>CTFESC está coformado por personas de <b>todos los niveles de conocimiento</b>. Nuestro objetivo es desarrollar las habilidades técnicas que nos permitan destacar en este sector.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url:

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags: ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - planteamiento_taller.md
  - lista_de_actividades.md
  - justificacion_y_objetivos.md
