# WhatATheme
markdown: kramdown

# URL of the Site
url: https://ctfesc.me 
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: CTFESC
# Description of the Site
#description: Grupo dedicado a la Ciberseguridad y Hacking Ético
description: Captura la bandera, captura la FESC
# URL of Image of the Site
site-image: https://cdn.pixabay.com/photo/2013/07/12/14/14/pirate-148043_960_720.png
# Keywords of the Site
site-keywords: Ciberseguridad, FESC, Hacking, CTF
# URL for the Image of custom Favicon
favicon-url: https://cdn.pixabay.com/photo/2013/07/12/14/14/pirate-148043_960_720.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# matrix
heroimage: https://cdn.pixabay.com/photo/2016/10/12/19/50/matrix-1735640_960_720.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: sth@protonmail.com
twitter_username:
instagram_username: /
linkedin_username:
github_username:
youtube_channel_id: /
reddit_username: /
discord_server: hack4u

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: /

# Name of the Author
author-name: CTFESC
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2013/07/12/14/14/pirate-148043_960_720.png
# 60 Words About the Author
author-about: Somos un grupo de alumnos y profesores de la FES Cuautitlán interesado en la Ciberseguridad y el Hacking Ético. Impulsamos el aprendizaje autodidacta a través de compartir conocimiento en la resolución de retos y máquinas de plataformas dedicadas al Pentesting como Hack The Box, Vulnhub y TryHackMe. <br>CTFESC está coformado por personas de todos los niveles de conocimiento. Todos comenzamos desde cero alguna vez, sabemos que la ciberseguridad puede parecer difícil al inicio, pero para hacerla menos intimidante nos juntamos. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url:

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags: ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
